
package com.unitn.bl_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.unitn.local_database.MeasureData;
import com.unitn.local_database.UserData;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BLService", targetNamespace = "http://bl_service.unitn.com/")
@XmlSeeAlso({
    chart.ObjectFactory.class,
    com.unitn.bl_service.ObjectFactory.class,
    com.unitn.local_database.ObjectFactory.class,
    com.unitn.storage_service.ObjectFactory.class
})
public interface BLService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.unitn.bl_service.NewStepResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveNewSteps", targetNamespace = "http://bl_service.unitn.com/", className = "com.unitn.bl_service.SaveNewSteps")
    @ResponseWrapper(localName = "saveNewStepsResponse", targetNamespace = "http://bl_service.unitn.com/", className = "com.unitn.bl_service.SaveNewStepsResponse")
    @Action(input = "http://bl_service.unitn.com/BLService/saveNewStepsRequest", output = "http://bl_service.unitn.com/BLService/saveNewStepsResponse")
    public NewStepResponse saveNewSteps(
        @WebParam(name = "arg0", targetNamespace = "")
        MeasureData arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDescription", targetNamespace = "http://bl_service.unitn.com/", className = "com.unitn.bl_service.GetDescription")
    @ResponseWrapper(localName = "getDescriptionResponse", targetNamespace = "http://bl_service.unitn.com/", className = "com.unitn.bl_service.GetDescriptionResponse")
    @Action(input = "http://bl_service.unitn.com/BLService/getDescriptionRequest", output = "http://bl_service.unitn.com/BLService/getDescriptionResponse")
    public String getDescription();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerNewUser", targetNamespace = "http://bl_service.unitn.com/", className = "com.unitn.bl_service.RegisterNewUser")
    @ResponseWrapper(localName = "registerNewUserResponse", targetNamespace = "http://bl_service.unitn.com/", className = "com.unitn.bl_service.RegisterNewUserResponse")
    @Action(input = "http://bl_service.unitn.com/BLService/registerNewUserRequest", output = "http://bl_service.unitn.com/BLService/registerNewUserResponse")
    public boolean registerNewUser(
        @WebParam(name = "arg0", targetNamespace = "")
        UserData arg0);

    /**
     * 
     * @param parameters
     * @return
     *     returns java.lang.Object
     */
    @WebMethod
    @WebResult(name = "statsResponse", targetNamespace = "http://bl_service.unitn.com/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://bl_service.unitn.com/BLService/statsRequest", output = "http://bl_service.unitn.com/BLService/statsResponse")
    public Object stats(
        @WebParam(name = "stats", targetNamespace = "http://bl_service.unitn.com/", partName = "parameters")
        Stats parameters);

}
