
package com.unitn.storage_service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.unitn.local_database.MeasureData;
import com.unitn.local_database.UserData;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StorageService", targetNamespace = "http://storage_service.unitn.com/")
@XmlSeeAlso({
    com.unitn.local_database.ObjectFactory.class,
    com.unitn.storage_service.ObjectFactory.class
})
public interface StorageService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveData", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.SaveData")
    @ResponseWrapper(localName = "saveDataResponse", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.SaveDataResponse")
    @Action(input = "http://storage_service.unitn.com/StorageService/saveDataRequest", output = "http://storage_service.unitn.com/StorageService/saveDataResponse")
    public void saveData(
        @WebParam(name = "arg0", targetNamespace = "")
        MeasureData arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.unitn.local_database.MeasureData>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLatestData", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.GetLatestData")
    @ResponseWrapper(localName = "getLatestDataResponse", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.GetLatestDataResponse")
    @Action(input = "http://storage_service.unitn.com/StorageService/getLatestDataRequest", output = "http://storage_service.unitn.com/StorageService/getLatestDataResponse")
    public List<MeasureData> getLatestData(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFromToStepsData", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.GetFromToStepsData")
    @ResponseWrapper(localName = "getFromToStepsDataResponse", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.GetFromToStepsDataResponse")
    @Action(input = "http://storage_service.unitn.com/StorageService/getFromToStepsDataRequest", output = "http://storage_service.unitn.com/StorageService/getFromToStepsDataResponse")
    public Integer getFromToStepsData(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.unitn.storage_service.Goal>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGoals", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.GetGoals")
    @ResponseWrapper(localName = "getGoalsResponse", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.GetGoalsResponse")
    @Action(input = "http://storage_service.unitn.com/StorageService/getGoalsRequest", output = "http://storage_service.unitn.com/StorageService/getGoalsResponse")
    public List<Goal> getGoals(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDescription", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.GetDescription")
    @ResponseWrapper(localName = "getDescriptionResponse", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.GetDescriptionResponse")
    @Action(input = "http://storage_service.unitn.com/StorageService/getDescriptionRequest", output = "http://storage_service.unitn.com/StorageService/getDescriptionResponse")
    public String getDescription();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userExists", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.UserExists")
    @ResponseWrapper(localName = "userExistsResponse", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.UserExistsResponse")
    @Action(input = "http://storage_service.unitn.com/StorageService/userExistsRequest", output = "http://storage_service.unitn.com/StorageService/userExistsResponse")
    public boolean userExists(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.unitn.local_database.UserData
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.GetUserResponse")
    @Action(input = "http://storage_service.unitn.com/StorageService/getUserRequest", output = "http://storage_service.unitn.com/StorageService/getUserResponse")
    public UserData getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveGoal", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.SaveGoal")
    @ResponseWrapper(localName = "saveGoalResponse", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.SaveGoalResponse")
    @Action(input = "http://storage_service.unitn.com/StorageService/saveGoalRequest", output = "http://storage_service.unitn.com/StorageService/saveGoalResponse")
    public boolean saveGoal(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Goal arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createUser", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.CreateUserResponse")
    @Action(input = "http://storage_service.unitn.com/StorageService/createUserRequest", output = "http://storage_service.unitn.com/StorageService/createUserResponse")
    public void createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        UserData arg0);

    /**
     * 
     * @return
     *     returns com.unitn.storage_service.XkcdComic
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRandomComic", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.GetRandomComic")
    @ResponseWrapper(localName = "getRandomComicResponse", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.GetRandomComicResponse")
    @Action(input = "http://storage_service.unitn.com/StorageService/getRandomComicRequest", output = "http://storage_service.unitn.com/StorageService/getRandomComicResponse")
    public XkcdComic getRandomComic();

    /**
     * 
     * @return
     *     returns com.unitn.storage_service.Quote
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMovieQuote", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.GetMovieQuote")
    @ResponseWrapper(localName = "getMovieQuoteResponse", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.GetMovieQuoteResponse")
    @Action(input = "http://storage_service.unitn.com/StorageService/getMovieQuoteRequest", output = "http://storage_service.unitn.com/StorageService/getMovieQuoteResponse")
    public Quote getMovieQuote();

    /**
     * 
     * @return
     *     returns com.unitn.storage_service.Quote
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFamousQuote", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.GetFamousQuote")
    @ResponseWrapper(localName = "getFamousQuoteResponse", targetNamespace = "http://storage_service.unitn.com/", className = "com.unitn.storage_service.GetFamousQuoteResponse")
    @Action(input = "http://storage_service.unitn.com/StorageService/getFamousQuoteRequest", output = "http://storage_service.unitn.com/StorageService/getFamousQuoteResponse")
    public Quote getFamousQuote();

}
