
package com.unitn.storage_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Storage", targetNamespace = "http://storage_service.unitn.com/", wsdlLocation = "https://radiant-chamber-78838.herokuapp.com/ws/storage?wsdl")
public class Storage
    extends Service
{

    private final static URL STORAGE_WSDL_LOCATION;
    private final static WebServiceException STORAGE_EXCEPTION;
    private final static QName STORAGE_QNAME = new QName("http://storage_service.unitn.com/", "Storage");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://radiant-chamber-78838.herokuapp.com/ws/storage?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STORAGE_WSDL_LOCATION = url;
        STORAGE_EXCEPTION = e;
    }

    public Storage() {
        super(__getWsdlLocation(), STORAGE_QNAME);
    }

    public Storage(WebServiceFeature... features) {
        super(__getWsdlLocation(), STORAGE_QNAME, features);
    }

    public Storage(URL wsdlLocation) {
        super(wsdlLocation, STORAGE_QNAME);
    }

    public Storage(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STORAGE_QNAME, features);
    }

    public Storage(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Storage(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StorageService
     */
    @WebEndpoint(name = "StorageServiceImplPort")
    public StorageService getStorageServiceImplPort() {
        return super.getPort(new QName("http://storage_service.unitn.com/", "StorageServiceImplPort"), StorageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StorageService
     */
    @WebEndpoint(name = "StorageServiceImplPort")
    public StorageService getStorageServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://storage_service.unitn.com/", "StorageServiceImplPort"), StorageService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STORAGE_EXCEPTION!= null) {
            throw STORAGE_EXCEPTION;
        }
        return STORAGE_WSDL_LOCATION;
    }

}
